### ISSUE TITLE
Unable to build with rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-20)

### ISSUE THREAD

**Issue by brutal-chaos** [docopt/docopt.rs#100]
0.6.38 is unable to build:
```
commit e54579e64d13e8a39946d964980554bd6b77350a (HEAD, tag: 0.6.38, origin/master, origin/HEAD, master)
```
```
~/repos/docopt.rs (master) $ cargo build
   Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling regex v0.1.15
   Compiling rustc-serialize v0.2.15
   Compiling docopt v0.6.38 (file:///home/chaos/repos/docopt.rs)

src/synonym.rs:2:34: 2:40 error: unresolved import `std::collections::hash_map::Hasher`. There is no `Hasher` in `std::collections::hash_map`
src/synonym.rs:2 use std::collections::hash_map::{Hasher, Iter, Keys};
                                                  ^~~~~~
error: aborting due to previous error
Could not compile `docopt`.

To learn more, run the command again with --verbose.
```

**Comment by brutal-chaos** [comment]
Closing, fixed by 05762ee314c404156ddbf67c789a988f91903ab6
