### ISSUE TITLE
docopt_macros failing to compile on rustc 1.16.0-nightly (4ecc85beb 2016-12-28)

### ISSUE THREAD

**Issue by benhinchley** [docopt/docopt.rs#205]
Running into a error when compiling the `docopt_macros` crate. I am honestly not to sure on how to fix the issue, but happy to work on a fix if someone can point me in the right direction.

**compiler error message**  
  ```
  Compiling docopt_macros v0.6.87
  error[E0560]: struct `syntax::ast::Path` has no field named `global`
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/docopt_macros-0.6.87/src/macro.rs:321:9
      |
  321 |         global: false,
      |         ^^^^^^^ `syntax::ast::Path` does not have this field

  error[E0308]: mismatched types
  --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/docopt_macros-0.6.87/src/macro.rs:324:25
      |
  324 |             parameters: ast::PathParameters::AngleBracketed(tystr),
      |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found enum `syntax::ast::PathParameters`
      |
      = note: expected type `std::option::Option<syntax::ptr::P<syntax::ast::PathParameters>>`
      = note:    found type `syntax::ast::PathParameters`

  error: aborting due to 2 previous errors
  error: Could not compile `docopt_macros`.
  ```

**Comment by BurntSushi** [comment]
It looks like this is breakage from the most recent nightly. The fix to this is to discover recent changes to Rust's internal `syntax` crate and then update the plugin here in this repo. Usually the docs for these internal crates are hosted [here](https://manishearth.github.io/rust-internals-docs/syntax/index.html), but it looks like they haven't been updated yet. cc @Manishearth

If this issue lingers long enough, then I'll fix it eventually, but I don't know when. I don't have the bandwidth to track nightly changes.

If stability of this crate is important to you, I'd recommend against using `docopt_macros`.

**Comment by benhinchley** [comment]
Thanks for the reply @BurntSushi I'll have a look and see if I can make the fix. Understand keeping up with nightly changes is a lot of work. Thanks 😄

**Comment by zsiciarz** [comment]
I've stumbled upon this as well and came up a fix in #206 if you're interested.
