### ISSUE TITLE
docopt_macros fails to build on rustc 1.7.0-nightly (42c3ef8f9 2015-12-22)

### ISSUE THREAD

**Issue by yberreby** [docopt/docopt.rs#160]
```
   Compiling docopt_macros v0.6.78 (file:///Users/yberreby/code/docopt.rs/docopt_macros)
src/macro.rs:18:5: 18:35 error: unresolved import `syntax::diagnostic::FatalError`. Could not find `diagnostic` in `syntax` [E0432]
src/macro.rs:18 use syntax::diagnostic::FatalError;
```

**Comment by BurntSushi** [comment]
fixed by #161
